category: 'usa_today'

news_api:
    endpoint: 'everything'
    params:
        q: 'hiv OR aids'
        qInTitle:
        sources:
        domains: 'usatoday.com'
        excludeDomains:
        from:
        to:
        language: 'en'
        sortBy: 'publishedAt'
        pageSize: 100

diffbot:
    params:
        fields:
        paging:
        maxTags:
        tagConfidence:
        discussion:
        timeout: 10000
        callback:
